// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmpaqjhpayfsfxauugto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcGFxamhwYXlmc2Z4YXV1Z3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTExNTAsImV4cCI6MjA2NzUyNzE1MH0.wsOS5czYDQMH_PevoMdK1tB0Ehn0GhjPwjOcE6LyCF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});